### ISSUE TITLE
Example:gyroid does not run

### ISSUE THREAD

**Issue by mattderstine** [JuliaGeometry/Meshing.jl#76]
I'm new, so sorry if this is known. I'm on JuliaPro, have cloned 0.5.4 after 0.5.3 in the package repository didn't work but I still get:

LoadError: MethodError: no method matching AbstractArray{GeometryBasics.Ngon{Dim,Float32,3,PointMeta{Dim,Float32,Point{Dim,Float32},(:normals,),Tuple{Vec{3,Float32}}}},1} where Dim(::var"#13#14", ::GeometryBasics.HyperRectangle{3,Float64}, ::MarchingCubes{Float64})

**Comment by sjkelly** [comment]
It is possible something may have changed in GeometryBasics or Makie since the 0.5.4 tag since they are fast moving targets. I'll check.

**Comment by mattderstine** [comment]
If I load master branch for GeometricBasics and Meshing it works

**Comment by sjkelly** [comment]
That is odd. I haven't made a commit to master since the 0.5.4 tag, but I wasn't able to reproduce either. 
BTW, GeometryBasics now supports the normal interface we rely on (so the view in Makie may be different than what is show on the docs page). To support this I will need to update the API. The docs will be updated accordingly, so check back or feel free to ping me if you have any difficulties.
